/* ###################################################################
 **     THIS COMPONENT MODULE IS GENERATED BY USER
 **     Filename    : LPF.h
 **     Project     : semg_mkl15z128vlh4
 **     Processor   : MKL15Z128VLH4
 **     Component   :
 **     Version     :
 **     Datasheet   :
 **     Compiler    : GNU C Compiler
 **     Date/Time   : 2014-Dec 5, 2014, 10:35:46 AM, # CodeGen: 1
 **     Author	    : Dong
 **     Abstract    :
 **			This file contains low pass filter functions.
 **     Settings    :
 **
 **     Contents    :
 **
 **     Mail      	: pzdongdong@163.com
 **
 **     Revision    : No.  Name        Data/Time        Content
 ** ###################################################################*/
/*!
 * @file LPF.h
 * @version 01.00
 * @brief
 *      This file contains low pass filter functions.
 */
/*!
 *  @addtogroup LPF Low Pass Filter
 *      This file contains low pass filter functions.
 *  @{
 */

#ifndef LPF_H_
#define LPF_H_

/* MODULE LPF */

/* {Default RTOS Adapter} No RTOS includes */
#include "Macros.h"
#include "PE_Types.h"

#ifdef __cplusplus
extern "C"
{
#endif

/*
 * ===================================================================
 *     Method      : EvenFirLPF ()
 */
/*!
 *     @brief
 *          The fir LPF, Hamming window. The order must be even.
 *          fs = 1000 Hz, fc = 380 Hz.
 *     @param[in]
 *          e               - The data to be filtered.
 *     @param[in]
 *          fq              - The filter buffer queue, a struct including queue pointers etc.
 *     @return
 *          short
 */
/* ===================================================================*/
int16 EvenFirLPF(register int16 const * const e, register TFilterBufferQueuePtr const fq);

/*
 * ===================================================================
 *     Method      : FirLPF40 ()
 */
/*!
 *     @brief
 *          The fir LPF, Hamming window.
 *          40th order, fs = 1000 Hz, fc = 380 Hz.
 *     @param[in]
 *          e           - The data to be filtered.
 *     @param[in]
 *          buffer      - The filter buffer.
 *     @return
 *          int
 */
/* ===================================================================*/
int32 FirLPF40(int16 const * const e, int16 * const buffer);


/* END LPF */

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
/* #ifndef LPF_H_ */

/*!
 * @}
 */
/*
 ** ###################################################################
 **
 **     This file was created by Dong
 **     for the Freescale Kinetis series of microcontrollers.
 **
 ** ###################################################################
 */
