var modules =
[
    [ "ADC module documentation", "group___a_d_c__module.html", "group___a_d_c__module" ],
    [ "Events module documentation", "group___events__module.html", "group___events__module" ],
    [ "User Initialization", "group___user_initialization.html", "group___user_initialization" ],
    [ "Low Pass Filter", "group___l_p_f.html", "group___l_p_f" ],
    [ "User Macros", "group___user_macros.html", "group___user_macros" ],
    [ "Process module documentation", "group___proc.html", "group___proc" ],
    [ "ProcessorExpert module documentation", "group___processor_expert__module.html", "group___processor_expert__module" ],
    [ "SPI Operation", "group___s_p_i___operation.html", "group___s_p_i___operation" ],
    [ "Test module documentation", "group___test__module.html", "group___test__module" ],
    [ "Utilities", "group___uti.html", "group___uti" ],
    [ "Alias", "group___ala.html", "group___ala" ],
    [ "Global Variables", "group___global_variables.html", "group___global_variables" ],
    [ "My Headers", "group___my_headers.html", null ],
    [ "Device and Environment Settings", "group___dev_env_set.html", "group___dev_env_set" ],
    [ "BitIO_AD_NOT_CS0 module documentation", "group___bit_i_o___a_d___n_o_t___c_s0__module.html", "group___bit_i_o___a_d___n_o_t___c_s0__module" ],
    [ "BitIO_AD_NOT_CS1 module documentation", "group___bit_i_o___a_d___n_o_t___c_s1__module.html", "group___bit_i_o___a_d___n_o_t___c_s1__module" ],
    [ "BitIO_AD_NOT_RESET0 module documentation", "group___bit_i_o___a_d___n_o_t___r_e_s_e_t0__module.html", "group___bit_i_o___a_d___n_o_t___r_e_s_e_t0__module" ],
    [ "BitIO_AD_NOT_RESET1 module documentation", "group___bit_i_o___a_d___n_o_t___r_e_s_e_t1__module.html", "group___bit_i_o___a_d___n_o_t___r_e_s_e_t1__module" ],
    [ "BitIO_AD_START0 module documentation", "group___bit_i_o___a_d___s_t_a_r_t0__module.html", "group___bit_i_o___a_d___s_t_a_r_t0__module" ],
    [ "BitIO_UPRDY module documentation", "group___bit_i_o___u_p_r_d_y__module.html", "group___bit_i_o___u_p_r_d_y__module" ],
    [ "Cpu module documentation", "group___cpu__module.html", "group___cpu__module" ],
    [ "DMA_CTRL module documentation", "group___d_m_a___c_t_r_l__module.html", "group___d_m_a___c_t_r_l__module" ],
    [ "DMAT_M_SPI_RX module documentation", "group___d_m_a_t___m___s_p_i___r_x__module.html", "group___d_m_a_t___m___s_p_i___r_x__module" ],
    [ "DMAT_M_SPI_TX module documentation", "group___d_m_a_t___m___s_p_i___t_x__module.html", "group___d_m_a_t___m___s_p_i___t_x__module" ],
    [ "DMAT_S_SPI_RX module documentation", "group___d_m_a_t___s___s_p_i___r_x__module.html", "group___d_m_a_t___s___s_p_i___r_x__module" ],
    [ "DMAT_S_SPI_TX module documentation", "group___d_m_a_t___s___s_p_i___t_x__module.html", "group___d_m_a_t___s___s_p_i___t_x__module" ],
    [ "EINT_AD_NOT_DRDY0 module documentation", "group___e_i_n_t___a_d___n_o_t___d_r_d_y0__module.html", "group___e_i_n_t___a_d___n_o_t___d_r_d_y0__module" ],
    [ "EINT_SYNC_INT module documentation", "group___e_i_n_t___s_y_n_c___i_n_t__module.html", "group___e_i_n_t___s_y_n_c___i_n_t__module" ],
    [ "PE_Const module documentation", "group___p_e___const__module.html", "group___p_e___const__module" ],
    [ "PE_Error module documentation", "group___p_e___error__module.html", "group___p_e___error__module" ],
    [ "PE_LDD module documentation", "group___p_e___l_d_d__module.html", "group___p_e___l_d_d__module" ],
    [ "PE_Types module documentation", "group___p_e___types__module.html", "group___p_e___types__module" ],
    [ "SM_SPI0 module documentation", "group___s_m___s_p_i0__module.html", "group___s_m___s_p_i0__module" ],
    [ "SS_SPI1 module documentation", "group___s_s___s_p_i1__module.html", "group___s_s___s_p_i1__module" ],
    [ "SysTick module documentation", "group___sys_tick__module.html", null ],
    [ "Vectors module documentation", "group___vectors__module.html", null ]
];