var modules =
[
    [ "ADC module documentation", "group___a_d_c__module.html", "group___a_d_c__module" ],
    [ "Events module documentation", "group___events__module.html", "group___events__module" ],
    [ "User Initialization", "group___user_initialization.html", "group___user_initialization" ],
    [ "User Macros", "group___user_macros.html", "group___user_macros" ],
    [ "Process module documentation", "group___proc.html", "group___proc" ],
    [ "ProcessorExpert module documentation", "group___processor_expert__module.html", "group___processor_expert__module" ],
    [ "SPI Operation", "group___s_p_i___operation.html", "group___s_p_i___operation" ],
    [ "Test module documentation", "group___test__module.html", "group___test__module" ],
    [ "Utilities", "group___uti.html", "group___uti" ],
    [ "BitIO_CLKSEL module documentation", "group___bit_i_o___c_l_k_s_e_l__module.html", "group___bit_i_o___c_l_k_s_e_l__module" ],
    [ "BitIO_DAISY_IN module documentation", "group___bit_i_o___d_a_i_s_y___i_n__module.html", "group___bit_i_o___d_a_i_s_y___i_n__module" ],
    [ "BitIO_NOT_PWDN module documentation", "group___bit_i_o___n_o_t___p_w_d_n__module.html", "group___bit_i_o___n_o_t___p_w_d_n__module" ],
    [ "BitIO_NOT_RESET module documentation", "group___bit_i_o___n_o_t___r_e_s_e_t__module.html", "group___bit_i_o___n_o_t___r_e_s_e_t__module" ],
    [ "BitIO_START module documentation", "group___bit_i_o___s_t_a_r_t__module.html", "group___bit_i_o___s_t_a_r_t__module" ],
    [ "BitIO_UPRDY module documentation", "group___bit_i_o___u_p_r_d_y__module.html", "group___bit_i_o___u_p_r_d_y__module" ],
    [ "Cpu module documentation", "group___cpu__module.html", "group___cpu__module" ],
    [ "CsIO_UART2 module documentation", "group___cs_i_o___u_a_r_t2__module.html", null ],
    [ "DMA_CTRL module documentation", "group___d_m_a___c_t_r_l__module.html", "group___d_m_a___c_t_r_l__module" ],
    [ "DMAT_M_SPI_RX module documentation", "group___d_m_a_t___m___s_p_i___r_x__module.html", "group___d_m_a_t___m___s_p_i___r_x__module" ],
    [ "DMAT_M_SPI_TX module documentation", "group___d_m_a_t___m___s_p_i___t_x__module.html", "group___d_m_a_t___m___s_p_i___t_x__module" ],
    [ "DMAT_S_SPI_RX module documentation", "group___d_m_a_t___s___s_p_i___r_x__module.html", "group___d_m_a_t___s___s_p_i___r_x__module" ],
    [ "DMAT_S_SPI_TX module documentation", "group___d_m_a_t___s___s_p_i___t_x__module.html", "group___d_m_a_t___s___s_p_i___t_x__module" ],
    [ "EINT_NOT_DRDY module documentation", "group___e_i_n_t___n_o_t___d_r_d_y__module.html", "group___e_i_n_t___n_o_t___d_r_d_y__module" ],
    [ "EINT_SYNC_INT module documentation", "group___e_i_n_t___s_y_n_c___i_n_t__module.html", "group___e_i_n_t___s_y_n_c___i_n_t__module" ],
    [ "IO2 module documentation", "group___i_o2__module.html", "group___i_o2__module" ],
    [ "PE_Const module documentation", "group___p_e___const__module.html", "group___p_e___const__module" ],
    [ "PE_Error module documentation", "group___p_e___error__module.html", "group___p_e___error__module" ],
    [ "PE_LDD module documentation", "group___p_e___l_d_d__module.html", "group___p_e___l_d_d__module" ],
    [ "PE_Types module documentation", "group___p_e___types__module.html", "group___p_e___types__module" ],
    [ "SM_SPI1 module documentation", "group___s_m___s_p_i1__module.html", "group___s_m___s_p_i1__module" ],
    [ "SS_SPI0 module documentation", "group___s_s___s_p_i0__module.html", "group___s_s___s_p_i0__module" ],
    [ "SysTick module documentation", "group___sys_tick__module.html", null ],
    [ "Vectors module documentation", "group___vectors__module.html", null ],
    [ "Alias", "group___ala.html", "group___ala" ],
    [ "Global Variables", "group___global_variables.html", "group___global_variables" ],
    [ "My Headers", "group___my_headers.html", null ],
    [ "Device and Environment Settings", "group___dev_env_set.html", "group___dev_env_set" ]
];