/* ###################################################################
 **     THIS COMPONENT MODULE IS GENERATED BY USER
 **     Filename    : LPF.h
 **     Project     : semg_mkl15z128vlh4
 **     Processor   : MKL15Z128VLH4
 **     Component   :
 **     Version     :
 **     Datasheet   :
 **     Compiler    : GNU C Compiler
 **     Date/Time   : 2014-Dec 5, 2014, 10:35:46 AM, # CodeGen: 1
 **     Author	    : Dong
 **     Abstract    :
 **			This file contains low pass filter functions.
 **     Settings    :
 **
 **     Contents    :
 **
 **     Mail      	: pzdongdong@163.com
 **
 **     Revision    : No.  Name        Data/Time        Content
 ** ###################################################################*/
/*!
 * @file LPF.h
 * @version 01.00
 * @brief
 *      This file contains low pass filter functions.
 */
/*!
 *  @addtogroup LPF Low Pass Filter
 *      This file contains low pass filter functions.
 *  @{
 */

#ifndef LPF_H_
#define LPF_H_

/* MODULE LPF */

/* {Default RTOS Adapter} No RTOS includes */


#ifdef __cplusplus
extern "C"
{
#endif

/*
 * ===================================================================
 *     Method      : Clear ()
 */
/*!
 *     @brief
 *         	Zeroize a FIR delay line.
 *     @param[in]
 *          ntaps       - The number of taps in the filter.
 *     @param[in, out]
 *          z           - The FIR delay line array.
 *     @return
 *         	void
 */
/* ===================================================================*/
void Clear(int ntaps, double z[]);

/*
 * ===================================================================
 *     Method      : FirBasic ()
 */
/*!
 *     @brief
 *          The basic fir LPF. Store input sample, calculate output
 *          sample, move delay line.
 *     @param[in]
 *          input       - The input sample.
 *     @param[in]
 *          ntaps       - The number of taps in the filter.
 *     @param[in]
 *          h           - The coefficients of LPF.
 *     @param[out]
 *          z           - The FIR delay line array.
 *     @return
 *          accum
 */
/* ===================================================================*/
double FirBasic(double input, int ntaps, const double h[], double z[]);


/* END LPF */

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
/* #ifndef LPF_H_ */

/*!
 * @}
 */
/*
 ** ###################################################################
 **
 **     This file was created by Dong
 **     for the Freescale Kinetis series of microcontrollers.
 **
 ** ###################################################################
 */
